using System.Text;

namespace Naadap.Alternative;

/// <summary>
/// Renders TP-260's comparison table (accuracy/precision@5, runtime,
/// token/compute cost for both approaches) as Markdown — the artifact
/// substantiating the non-LLM core's selection for DELIV-970's algorithm
/// documentation (docs/RTVM.md CORE-260, "Analysis" verification method).
/// </summary>
public static class ComparisonReportWriter
{
    public static string BuildMarkdown(
        string inputDescription,
        int documentCount,
        int skippedFileCount,
        ApproachRunResult core,
        ApproachRunResult alternative)
    {
        var sb = new StringBuilder();

        sb.AppendLine("# CORE-260 alternative-approach comparison");
        sb.AppendLine();
        sb.AppendLine(
            $"Generated by `Naadap.Alternative` against `{inputDescription}` " +
            $"({documentCount} document(s) ingested, {skippedFileCount} skipped).");
        sb.AppendLine();
        sb.AppendLine("| Approach | Clusters | Candidates | Clustering time | Total time | precision@5 | Correct/Total | LLM tokens used |");
        sb.AppendLine("| --- | --- | --- | --- | --- | --- | --- | --- |");
        AppendRow(sb, core);
        AppendRow(sb, alternative);
        sb.AppendLine();
        sb.AppendLine("## Metric definitions");
        sb.AppendLine();
        sb.AppendLine($"- **{core.ApproachName}:** {core.Metric.Definition}");
        sb.AppendLine($"- **{alternative.ApproachName}:** {alternative.Metric.Definition}");

        return sb.ToString();
    }

    private static void AppendRow(StringBuilder sb, ApproachRunResult result)
    {
        var precisionText = result.Metric.Value is { } value ? value.ToString("F2") : "n/a";
        sb.AppendLine(
            $"| {result.ApproachName} | {result.ClusterCount} | {result.CandidateCount} | " +
            $"{result.ClusteringElapsed.TotalMilliseconds:F1} ms | {result.TotalElapsed.TotalMilliseconds:F1} ms | " +
            $"{precisionText} | {result.Metric.CorrectCount}/{result.Metric.TotalCount} | {result.LlmTokensUsed} |");
    }
}
